volumes:
  solvego-db-data:
  solvego-prometheus-data:
  solvego-grafana-data:

services:
  db:
    image: mysql:8.0
    container_name: solvego-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: solvego
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - solvego-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.4-alpine
    container_name: solvego-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solvego-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CACHE_TYPE: ${CACHE_TYPE:-redis}
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://db:3306/solvego
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: solvego-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - solvego-prometheus-data:/prometheus
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: solvego-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - solvego-grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

